# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

default:
    image: 
        name: amazon/aws-cli:2.2.29
        entrypoint: [""]

stages:
    - build
    - deploy

# -== Global ==-

build:
    stage: build
    image: node:latest
    only:
        - master
        - staging
    cache:
        paths:
            - node_modules/
    artifacts:
        paths:
            - dist/
    script: 
        |
        yarn install
        yarn run build

# --= Staging =--

deploy::staging:
    stage: deploy
    only:
        - staging
    script:
        - aws s3 cp dist s3://${AWS_S3_OBJECT_PATH} --recursive


# --= Production =--

deploy::production:
    stage: deploy
    only:
        - master
    script:
        - aws s3 cp dist s3://${AWS_S3_OBJECT_PATH} --recursive
